apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
